### ISSUE TITLE
...Think you installed the wrong package

### ISSUE THREAD

**Issue by jimmywarting** [serra-allgood/react-useintersection#9]
should probably uninstall this package

https://github.com/serra-allgood/react-useintersection/blob/2ec803989dbb7474784b7c5d31d00146ea22a774/package.json#L58

**Comment by serra-allgood** [comment]
It was probably the correct package at the time. I'll see about upgrading it later.

**Comment by jimmywarting** [comment]
nope, it never was the correct one. (Just giving u a heads up that it could do something harmful later on...)

**Comment by serra-allgood** [comment]
Hm, thanks for the heads up!
